# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Python-Modules add-on
version: "1.0"
slug: pythom_modules
description: Python-Modules add-on
url: "https://github.com/home-assistant/homeassistant-addons/tree/main/python-modules"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: "services"
boot: "auto"
hassio_api: true
homeassistant_api: true
options:
  include_zones:
    - "Living Room"
  include_domains:
    - "light"
    - "switch"
  dependencies:
    switch.pc_outlet:
      - entity_id: "switch.pc"
        delay: 5
      - entity_id: "device_tracker.pc_tracker"
        delay: 10
      - entity_id: "sensor.pc_temperature"
    light.strip:
      - entity_id: "switch.pc_outlet"
  exclude_identifiers:
    - "browser_mod"
  exclude_entities:
    - "switch.eve_energy_lock"
  max_retries: 12
  retry_interval: 10
schema:
  include_zones:
    - "str"
  include_domains:
    - "str"
  dependencies:
    type: "dict"
  exclude_identifiers:
    - "str"
  exclude_entities:
    - "str"
  max_retries: "int"
  retry_interval: "int"
