# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Python-Modules add-on
version: "1.0"
slug: pythom_modules
description: Python-Modules add-on
url: "https://github.com/home-assistant/homeassistant-addons/tree/main/python-modules"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "ghcr.io/home-assistant/{arch}-addon-example"
